// Provenance: Extracted and adapted from ~/teamwork_projects/guadalupe_mass_interactive
/**
 * Subproject 2: Mass Transcript Mining & Curation Tool
 * Ingestion and sanitization of raw YouTube video auto-subtitle transcripts.
 */

import * as fs from 'node:fs';
import type { RawTranscriptCue, CleanTranscriptCue } from './types.ts';

// Regex patterns to identify non-speech annotations generated by automated subtitle engines
const SOUND_TAG_REGEX = /\[(Música|Musica|Aplausos|Risas|Silencio|Gritos|Campanas)\]/gi;
const BRACKETED_NOISE_REGEX = /\[[^\]]+\]/g;

/**
 * Cleans individual transcript cue text by stripping automated audio/sound tags
 * and normalizing internal whitespace.
 */
export function cleanCueText(rawText: string): string {
  if (!rawText) return '';

  let sanitized = rawText
    .replace(SOUND_TAG_REGEX, ' ')
    .replace(BRACKETED_NOISE_REGEX, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  return sanitized;
}

/**
 * Determines whether a cue consists exclusively of non-speech sound tags (e.g. [Música]).
 */
export function isMusicOrSoundCue(rawText: string): boolean {
  if (!rawText) return true;
  const cleaned = cleanCueText(rawText);
  return cleaned.length === 0;
}

/**
 * Ingests an array of raw YouTube transcript cues, sanitizes text,
 * tags music-only cues, and filters empty non-speech segments.
 */
export function ingestRawTranscript(cues: RawTranscriptCue[]): CleanTranscriptCue[] {
  if (!Array.isArray(cues)) {
    throw new Error('ingestRawTranscript: Expected array of cues');
  }

  const result: CleanTranscriptCue[] = [];

  for (const cue of cues) {
    const isMusic = isMusicOrSoundCue(cue.text);
    const cleanedText = cleanCueText(cue.text);

    // Keep cue with sanitized text, or omit if entirely empty
    if (cleanedText.length > 0) {
      result.push({
        start: cue.start,
        end: cue.end,
        startSeconds: cue.startSeconds,
        endSeconds: cue.endSeconds,
        text: cleanedText,
        isMusicOnly: isMusic,
      });
    }
  }

  return result;
}

/**
 * Ingests a raw transcript JSON file from disk.
 */
export function ingestTranscriptFromFile(filePath: string): CleanTranscriptCue[] {
  if (!fs.existsSync(filePath)) {
    throw new Error(`ingestTranscriptFromFile: File not found: ${filePath}`);
  }

  const rawJson = fs.readFileSync(filePath, 'utf-8');
  const rawCues = JSON.parse(rawJson) as RawTranscriptCue[];
  return ingestRawTranscript(rawCues);
}

/**
 * Filters cues occurring within a specific timestamp window [startSec, endSec].
 */
export function findCuesInRange(
  cues: CleanTranscriptCue[],
  startSec: number,
  endSec: number
): CleanTranscriptCue[] {
  return cues.filter(
    (cue) => cue.startSeconds >= startSec && cue.endSeconds <= endSec
  );
}

/**
 * Merges contiguous transcript cues into a single cohesive string.
 */
export function consolidateCuesText(cues: CleanTranscriptCue[]): string {
  return cues
    .map((c) => c.text)
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
}
